### ISSUE TITLE
Create Custom Axis Labels

### ISSUE THREAD

**Issue by SleepWalker** [reaviz/reaviz#1]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

**This is a copy-paste from jask-oss original issue**

When putting an SVG or SVG partial into the `format` property, they do not appear because they are put inside a `title` tag.

## Expected behavior

Putting an SVG into the `format` property will render it properly (maybe even extend this to normal HTML with `<foreignObject>`.

## Minimal reproduction of the problem with instructions

https://codesandbox.io/s/reaviz-bar-demo-x2b24

- Return an SVG inside the format property.
- SVG does not appear because it's embedded in a title

## What is the motivation / use case for changing the behavior?

Having icons for labels instead of text can improve the look and feel of charts.

**Comment by SleepWalker** [comment]
Here are some more historical comments:

![image](https://user-images.githubusercontent.com/2536916/80989417-93150900-8e3d-11ea-9dbd-adc395c38c4f.png)

https://github.com/reaviz/reaviz/blob/master/src/common/Axis/LinearAxis/LinearAxisTickLabel.tsx#L168

**Comment by SleepWalker** [comment]
And my own comment from the original issue:

Hello, I've tried to re-write `PieArcLabel` to add support for `foreignObject` and here are the results:

![image](https://user-images.githubusercontent.com/2536916/80062878-61e33180-853d-11ea-81ce-b8b6fc37e36f.png)

In order to achieve this you need some additional tweaks:

- horizontal margins should be increased, because label positioning in `PieChart` does not account for actual label size
- I have also extended `PieArcSeries`, because [`minDistance`](https://github.com/jask-oss/reaviz/blob/master/src/PieChart/PieArcSeries/PieArcSeries.tsx#L69) must be changed to add more vertical spacing for labels
- if you use HTML for label, you need to set fixed size or add `white-space: nowrap;` (I can't find a better way for sizing `foreignObject` rather than `position: absolute;`)

So, for this feature to work with `PieChart` there should additionally be provided at least a way to change `minDistance` constant and probably there is a better way for positioning `foreignObject`, but I'm lacking in expertise for that.

If this feature is still planned to be implemented, I would like to help with implementing it.

BTW. If we pass label position data in `format` function, it will also make possible to e.g. place the icons near the line, that connects with chart.

**Comment by amcdnl** [comment]
Yes! Please make a PR - I'm happy to accept! This looks great BTW!

**Comment by SleepWalker** [comment]
Hello, will try to implement this issue during this month.

**Comment by amcdnl** [comment]
@SleepWalker - can you share that code and I can help fix the delta in the library?

**Comment by SleepWalker** [comment]
@amcdnl I've submitted my current progress as a PR. It's still not ready, but I think this is a time to receive some feedback about my implementation decisions,
