### ISSUE TITLE
Scatter Plot Grid Lines missing stripe

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reaviz#102]
![image](https://user-images.githubusercontent.com/227909/207085415-c630bf2f-6bc1-487c-ba23-9077dfc92e10.png)

The stripe is missing on this last one.

**Comment by evgenoid** [comment]
Looks like first line of axis is missing for all grids
<img width="755" alt="Screenshot 2022-12-27 at 10 33 11" src="https://user-images.githubusercontent.com/1290843/209637754-949a3b3f-fe6b-4b4c-a7cc-b6e59c30bc7b.png">
<img width="761" alt="Screenshot 2022-12-27 at 10 33 19" src="https://user-images.githubusercontent.com/1290843/209637766-5f6cccba-7fc4-4d16-bf56-721a751ec1ec.png">
