### ISSUE TITLE
Feature Stacked Radial Gauge

### ISSUE THREAD

**Issue by pfried** [reaviz/reaviz#17]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Feature Stacked Radial Gauge

The Stacked Radial Gauge renders a series of `ChartShallowDataShape` within `RadialGauge`

![image](https://user-images.githubusercontent.com/1744875/99781996-e2403400-2b18-11eb-97c1-f0ca29487ab8.png)

There are some properties to control the `StackedRadialGaugeSeries`

### fillFactor

fillFactor = 0.3 | fillFactor = 1
------------ | -------------
![image](https://user-images.githubusercontent.com/1744875/99782505-8924d000-2b19-11eb-9fcf-03045b1c3356.png)  | ![image](https://user-images.githubusercontent.com/1744875/99782576-a22d8100-2b19-11eb-99eb-e140a18a798c.png)

### arcPadding
arcPadding = 0 | arcPadding = 0.5
------------ | -------------
![image](https://user-images.githubusercontent.com/1744875/99782844-fa648300-2b19-11eb-94af-627c203d9ba0.png) | ![image](https://user-images.githubusercontent.com/1744875/99782718-d1dc8900-2b19-11eb-81ed-7d6a5fadc7d9.png)

## What is the motivation / use case for changing the behavior?

We need this for our own application

## Issues

The Tooltip of the Arcs might not be great, maybe I it should be removed in favor of showing the value below the label (There needs to be space for it, might not be possible everywhere)

Current Tooltip (form `RadialGaugeArc`)
![image](https://user-images.githubusercontent.com/1744875/99782988-21bb5000-2b1a-11eb-8400-9fa378378410.png)

**Comment by amcdnl** [comment]
I love this! Amazing work!!!!

so for tooltips - what about doing something similar to the stacked bar charts where it shows them all in one tooltip? You can do that w/ this tooltip already - you just need to pass the data to it in a way it can understand its a multi series. Another idea could be changing the inner text to the item you are hovering?

Also what do other libraries do?
