### ISSUE TITLE
Scatter Plot - Trend Line

### ISSUE THREAD

**Issue by jdeitsch** [reaviz/reaviz#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Current Scatter Plot appears to have no method of generating a dynamic trend line based on the datapoints provided.

## Expected behavior

It would be a very useful feature to be able to dynamically generate a trend line within the scatter plot in order to clearly show to the users the trend of the data provided.

## Minimal reproduction of the problem with instructions
No reproduction, feature does not currently exist

## What is the motivation / use case for changing the behavior?

I have a huge quantity of pricing data that I need to visualize for my users, a dynamic trend line would allow them to see the pricing trends as well as use filtering of the data through other means to adjust that trend line in realtime in order to visualizehow changes to their datasets will potentially benefit them longterm

## Environment

<pre><code>
Libs:
- react version: 18.2.0
- reaviz version: 15.8.1

</code></pre>

**Comment by amcdnl** [comment]
I believe this is what you want: https://reaviz.io/?path=/story/charts-scatter-plot-markers--linear-value-markers

**Comment by jdeitsch** [comment]
My need is for something a little more robust than a single horizontal line.
Ideally something that can curve to show the trends in data, rather than simply marking out a single horizontal line.
Is that something I can do with the `LinearValueMarker`?

<img width="785" alt="scatter with trend lines" src="https://github.com/reaviz/reaviz/assets/6425715/f3e750f3-c1fc-4499-9a43-f071602fd191">

**Comment by amcdnl** [comment]
This seems like more of a multi chart - where a line + scatter scenario.
