### ISSUE TITLE
CalendarHeatmap is not showing last 17 days of data

### ISSUE THREAD

**Issue by devconn99** [reaviz/reaviz#237]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`CalendarHeatmap` is not showing last 17 days

## Expected behavior
Expecting the `CalendarHeatmap` to fully show the data

## Minimal reproduction of the problem with instructions
          <CalendarHeatmap
            height={200}
            data={calendarData}
            series={
              <HeatmapSeries
                colorScheme={CALENDAR_COLOR_SCHEME}
                padding={0.3}
              />
            }
          />
        )}

STEPS TO REPRODUCE
1. Add the data below to the `CalendarHeatmap`

## Environment
Windows 10
Google Chrome

<pre><code>
Libs:
- react version: 18.2.0
- reaviz version: 15.15.6
- Node version: 20.15.0

Most recent version have this issue too
</code></pre>

When I'm using import { heatmapCalendarData } from 'reaviz-data-utils'; as data everything works fine, but when I put the data below it's not showing the last 17 days
![ejtysbrafd](https://github.com/user-attachments/assets/9d5e0a1c-d11a-418b-833e-05137da50100)

[data.txt](https://github.com/user-attachments/files/16274352/data.txt)

**Comment by cloughrm** [comment]
Commenting for my own visibility here

**Comment by amcdnl** [comment]
Can you share the data you used to make this chart?

**Comment by devconn99** [comment]
[data (1).txt](https://github.com/user-attachments/files/16337086/data.1.txt)

Please wrap `key` inside `new Date()`
