### ISSUE TITLE
Missing sample dataset in storybook how we know data shape please add sample data sets in all e

### ISSUE THREAD

**Issue by Abhijit47** [reaviz/reaviz#242]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Other... Please describe: 
Missing sample dataset in storybook how we know data shape please add sample data sets in all example in storybook
</code></pre>

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- reaviz version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
Docs have been moved to - https://reaviz.dev/docs/getting-started/data
