### ISSUE TITLE
Cannot find name 'PointObjectNotation'

### ISSUE THREAD

**Issue by mjoppich** [reaviz/reaviz#28]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Build errors with error message:

ERROR in [at-loader] ./node_modules/reaviz/dist/src/common/utils/position.d.ts:23:71
        TS2304: Cannot find name 'PointObjectNotation'.

## Expected behavior
Adding reaviz to package.json allows me to use the package in my project.

The problem here is typescript, which automatically creates the definitions. Unfortunately it does not find type information for 

`export declare const getPointFromMatrix: (event: any, matrix: any) => PointObjectNotation`

I guess this could be circumvented by either defining the type yourself:

`type PointObjectNotation = { x: number; y: number };`

Or importing it from transformation-matrix directly.

I can not guarantee that this is not a problem on my end, but I can understand that typescript does not like the missing type information ...

**Comment by amcdnl** [comment]
interesting - ok - need to think about how to do that since its a nested type - i would have thought it would have just re-exported it for me.

**Comment by mjoppich** [comment]
Yeah, all I can contribute is that if I add

`type PointObjectNotation = { x: number; y: number };`

to `./node_modules/reaviz/dist/src/common/utils/position.d.ts` it works :)
