### ISSUE TITLE
Can't resolve 'framer-motion' in 'app\node_modules\rdk\dist'

### ISSUE THREAD

**Issue by Rocinante89** [reaviz/reaviz#30]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Updating to the latest version of reaviz causes a compile error

**Comment by amcdnl** [comment]
Hmmm - you might need to install framer-motion yourself - I moved it to a peer dependency because of resolution issues between things.

**Comment by Rocinante89** [comment]
@amcdnl cheers, that sorted it!
