### ISSUE TITLE
Bar Chart is missing view on Chrome new version 

### ISSUE THREAD

**Issue by akinayturan** [reaviz/reaviz#34]
<img width="1104" alt="Screen Shot 2021-01-22 at 17 30 21" src="https://user-images.githubusercontent.com/3206344/105503344-82603800-5cd7-11eb-8366-05c1b35814c1.png">

Browser:
- [ x ] Chrome (desktop) Version 88.0.4324.96 (Official Build) (x86_64)

i checked on firefox and safari is working ^^

maybe help

<img width="1511" alt="Screen Shot 2021-01-22 at 17 36 59" src="https://user-images.githubusercontent.com/3206344/105504123-70cb6000-5cd8-11eb-9cff-839c2d184a30.png">

**Comment by amcdnl** [comment]
Framer motion is a peer dependency. I think you need to install it.

**Comment by akinayturan** [comment]
that image and log from your page ^^

https://reaviz.io/?path=/docs/docs-chart-types-bar-chart--page

**Comment by amcdnl** [comment]
Fixed.

**Comment by akinayturan** [comment]
<img width="1271" alt="Screen Shot 2021-01-22 at 18 04 24" src="https://user-images.githubusercontent.com/3206344/105507456-44194780-5cdc-11eb-8132-4f97dda99dbd.png">

**Comment by amcdnl** [comment]
Needs to deploy - give it a few :D

**Comment by akinayturan** [comment]
haha ty :)
