### ISSUE TITLE
Hover elements render below the bar chart if the chart is not on top of the page

### ISSUE THREAD

**Issue by alparius** [reaviz/reaviz#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If a bar chart is further down in a longer page, the hover element showing the data values on the chart is rendered much below the chart, sometimes even extending below the length of the page, below the footer.

## Expected behavior

It should always show these elements on the chart. Pie charts for example work fine.

## Minimal reproduction of the problem with instructions
Create a page with a bar chart further down in it.
**UPDATE**: [codesandbox](https://codesandbox.io/s/reaviz-hover-elements-render-below-the-chart-forked-7gz2y)

## Environment

<pre><code>
Libs:
- react version: 16.13.1
- reaviz version: 8.1.3

Browser:
- [x] Chrome (desktop) version 83
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 77
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 83
 
For Tooling issues:
- Node version: 13.8.0  
- Platform: Windows

</code></pre>

**Comment by amcdnl** [comment]
Can you make a demo?

**Comment by sooendre** [comment]
Hey @amcdnl , 

I can make one for you. Here is a chart not exactly on the top of my page. When I hover the orange chart the tooltip doesn't appear where I pointed the mouse, but way below it: https://ibb.co/H73SBTJ

Do you have any idea what could've caused such a behaviour. Maybe I'm missing some classes or settings for the chart.

Thanks!

**Comment by alparius** [comment]
Thank you @sooendre for the evidence, this issue is exactly what I'm experiencing.

And also thank you for reminding me of this issue. Lately, I haven't had the time for this passion project of mine using this library, but will try to make a jsfiddle to set things in motion.

**Comment by alparius** [comment]
So I ended up borrowing an already configured codesandbox environment from [an other issue](https://github.com/reaviz/reaviz/issues/1) here and reproducing the bug was as easy as bumping up the version to the mentioned **8.1.3** and inserting some text fields before the chart.

[codesandbox](https://codesandbox.io/s/reaviz-hover-elements-render-below-the-chart-forked-7gz2y)

Also tried it out with the latest 8.2.0 release and the issue stays.

**Comment by amcdnl** [comment]
Done in 9.0.2

**Comment by alparius** [comment]
@amcdnl are you sure though? The codesandbox still has the same problem. What are the other dependencies' versions in your environment?

**Comment by alex20044** [comment]
I am experiencing the same issue with the latest version.
