### ISSUE TITLE
Sankey white background bug

### ISSUE THREAD

**Issue by kairan** [reaviz/reaviz#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I m using the simple sankey example from the docs using a white background.

## Expected behavior
see the chart

## Minimal reproduction of the problem with instructions
PROBLEM REPRODUCED 
https://codesandbox.io/s/snowy-meadow-wk1vd

## Environment

<pre><code>
Libs:
- react version: 16.8.0
- reaviz version: 10.2.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform: Mac  

Others:

</code></pre>

**Comment by linden-dg** [comment]
More specifically, this is due to the `mix-blend-mode: screen` at https://github.com/reaviz/reaviz/blob/9da8b98c8a1616a0b1710c5d4860ea4e002089ed/src/Sankey/SankeyLink/SankeyLink.module.css#L4

If I change it to `mix-blend-mode: initial` then it works fine on a white background.

**Comment by amcdnl** [comment]
Just fixed in latest.
