### ISSUE TITLE
Update CalendarHeatmap documentation

### ISSUE THREAD

**Issue by oscarlofwenhamn** [reaviz/reaviz#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Using the current code and sample data from the CalendarHeatmap code at [Reaviz Charts page](https://reaviz.io/?path=/docs/charts-heatmap-calendar--year-calendar) gives the Error `Uncaught TypeError: date.getFullYear is not a function`. When instead passing the keys as Date objects, it renders. The docs and sample data should be updated to reflect this.

**Comment by oscarlofwenhamn** [comment]
I could find the [cached version](https://webcache.googleusercontent.com/search?q=cache:f9jNgpxbDYsJ:https://github.com/jask-oss/reaviz/issues/130+&cd=1&hl=en&ct=clnk&gl=se ) of the same issue from the last repo with the following reply:

> Hi @elimist3. This component actually requires Date instances to be passed as keys in the data. I forked your codesandbox here and converted the keys to date and it works:
>
>https://codesandbox.io/s/reaviz-codesandbox-template-6ew0d

Seems to work in my case as well, but I reckon the docs can still do with an update reflecting this.

**Comment by amcdnl** [comment]
Can you verify if this works now?

**Comment by oscarlofwenhamn** [comment]
Verified, sample data now works as-is, nice!
