### ISSUE TITLE
Setting VennLabel as null doesn't work

### ISSUE THREAD

**Issue by noamantebi** [reaviz/reaviz#66]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

According to your documentation this is possible to set series label as null. 
But actually when setting null, we receive an error.

## Expected behavior

render Venn diagram without a label

## Minimal reproduction of the problem with instructions

See this demo.
https://codesandbox.io/s/reaviz-codesandbox-template-forked-hqefg3?file=/src/App.js:375-379

## Environment

<pre><code>
Libs:
- react version: 17.0.2
- reaviz version: 12.2.0

Browser: all

**Comment by amcdnl** [comment]
It should not render this at all if null.
