### ISSUE TITLE
Setting minimum and maximum values on area & line charts

### ISSUE THREAD

**Issue by Zaya1101** [reaviz/reaviz#73]
Is it possible to implement props for min and max values of the y-axis scale on area and line charts? It seems at the moment all area and line charts have a y-axis that always starts at 0.

**Comment by amcdnl** [comment]
Yes - Example:

```
yAxis={
              <LinearYAxis
                domain={[0, 100]}
                axisLine={null}
                position="end"
                tickSeries={<LinearYAxisTickSeries line={null} label={null} />}
              />
```

In the future, please ask ?s in the Discussions please.
