### ISSUE TITLE
Treemap label wrapping not working

### ISSUE THREAD

**Issue by motykadaw** [reaviz/reaviz#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When the treemap label is longer than it's rect, it doesn't wrap and instead just disappears.

## Expected behavior

Labels wrap nicely.

## Minimal reproduction of the problem with instructions
I've checked the current shape of the `wrapText` function [here](https://github.com/reaviz/reaviz/blob/master/src/common/utils/wrapText.tsx) and while looping over the words, in lines 33 and 38 it always adds the word width to the sum. It then compares `sumWidth` to container width in line 52 and if we need wrapping, it's obviously longer, so it returns `null`.
Since `wrapText` is used in different charts as well and I've just started using reaviz, I'm probably not the person to fix it so I don't cause any regressions.
```
const simpleData: ChartShallowDataShape[] = [
    {
      key: "Very long text, make it as long as necessary or shrink the treemap width so it's longer than the rect's width.",
      data: 1,
    },
    ]
    
     return <TreeMap
      height={400}
      data={simpleData}
      margins={20}
      series={
        <TreeMapSeries  />
      }
    />
```

## Environment

<pre><code>
Libs:
    "react": "17.0.2",
    "reaviz": "13.1.3"
Others:

</code></pre>

**Comment by motykadaw** [comment]
Side comment: it seems like a good opportunity to introduce on-demand wrapping while fixing this one, how would you feel about parsing `\n`s into subsequent rows?

**Comment by amcdnl** [comment]
This logic is pretty tricky - I fought w/ it for a bit. I'm open to any suggestions you might have.

**Comment by motykadaw** [comment]
This has to account for all the other stuff that's in there and I made a comfortable assumption that `wordWidth === word.length`, but maybe this would work:
```
const getRows = (text: string, maxRowWidth: number): string[] | null => {
  const words = text.split(" ");
  if (words.some((w) => w.length > maxRowWidth)) {
    // if any single word if too long, just null
    return null;
  }

  return words.reduce<string[]>(
    (rows, word) => {
      const currentRow = rows[rows.length - 1];
      return currentRow.length + word.length > maxRowWidth
        ? [...rows, word] // add row if the next word would cause overflow
        : [...rows.slice(0, -1), `${currentRow} ${word}`]; // add the word to last row
    },
    [""]
  );
};
```

**Comment by amcdnl** [comment]
> I made a comfortable assumption that wordWidth === word.length

Ya, you can't do this. Fonts can vary dramatically. The library already does some measuring of the text that you should be able to use.

**Comment by puripant** [comment]
Hi, I am new to this repo but would like to contribute, especially to this issue. I looked into `wrapText.tsx` and found a few things that made it not working for treemap. For example, the sum of word widths (plus spaces) was not the same as running `calculateDimensions()` on the whole sentence, probably due to kerning and such. `paddingX` had no default value and could be `undefined` and etc. I edited `wrapText()` as follows.

```JavaScript
for (const word of words) {
  nextText = curText === "" ? word : `${curText} ${word}`;
  nextWidth = calculateDimensions(nextText, fontFamily, fontSize).width;
  
  if (nextWidth <= width - (paddingX ? 2*paddingX : 0)) {
    curText = nextText;
    currWidth = nextWidth;
  } else {
    rows.push(curText);
    maxWidth = Math.max(maxWidth, currWidth);
    curText = word;
    currWidth = calculateDimensions(curText, fontFamily, fontSize).width;
  }
}
rows.push(curText);
maxHeight = rows.length * size.height;
```

I also wrote a treemap example with long text labels in the Storybook to test it. `wrapText()` was used in two other charts: bubble chart and Venn diagram. I checked their examples with long label texts and they worked fine as well.

If this sounds okay, I can create a pull request.

**Comment by amcdnl** [comment]
@puripant - We would welcome any contributions!
