### ISSUE TITLE
Robinson-style Map Projection

### ISSUE THREAD

**Issue by aeksco** [reaviz/reaviz#90]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `Map` component only supports a [Mercator projection](https://en.wikipedia.org/wiki/Mercator_projection).

## Expected behavior
It would be great if the `Map` component could optionally render as a [Robinson projection](http://en.wikipedia.org/wiki/Robinson_projection)-style chart.

For the version of `d3-geo` used in Reviz, the [`geoNaturalEarth` projection](https://github.com/d3/d3-geo#geoNaturalEarth1) is pretty close.

## Minimal reproduction of the problem with instructions

Here's a test of this change in Storybook:

![Screen Shot 2022-10-06 at 3 41 48 PM](https://user-images.githubusercontent.com/4616233/194405258-44b50ee4-35ab-4985-93a1-e648fd7c0cef.png)

And the original Mercator projection for contrast:

![Screen Shot 2022-10-06 at 3 52 29 PM](https://user-images.githubusercontent.com/4616233/194406018-1f032ea7-ac33-4f31-b8ae-557c55b28e06.png)

I was able to smoke-test this by importing a the `geoNaturalEarth1` projection function from `d3-geo`:

![Screen Shot 2022-10-06 at 3 44 08 PM](https://user-images.githubusercontent.com/4616233/194404613-ff6a4108-0239-411d-bd69-40f6aa104e07.png)

It would be a trivial addition to add an optional `projection` prop to `MapProps` to support this feature:

```tsx
interface MapProps extends ChartProps {
  markers?: MarkerElement[];
  data: any;
  fill?: string;
  projection?: "mercator" | "natural-earth"
}

```

## What is the motivation / use case for changing the behavior?

The Mercator projection inflates the size of objects further away from the equator - notably this results in Greenland being inflated significantly. It would be exciting for the `Map` component to have more versatility and I think supporting a more varied selection of projections would be an awesome place to start! 

I'd be happy to raise a PR with this addition - let me know your thoughts, and thanks for all the terrific work on Reaviz!

**Comment by aeksco** [comment]
@amcdnl Bump here!

**Comment by adamlawrencium** [comment]
Would also enjoy this modification too 😄

**Comment by amcdnl** [comment]
Yes happy to accept a PR - sorry I was on vacation!
