### ISSUE TITLE
Export Scales

### ISSUE THREAD

**Issue by alexdriedger** [reaviz/reaviz#94]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Scales from common/scales are not exported. The export is missing in `/src/common/index.ts`. This makes it harder to follow some of the docs (Bar chart axis examples) since `getXScale` and `getYScale` are not available to import.

## Expected behavior

Scales are exported as part of the library

## Minimal reproduction of the problem with instructions
`import { getXScale } from "reaviz" `

Error log:
> export 'getXScale' (imported as 'getXScale') was not found in 'reaviz'

## What is the motivation / use case for changing the behavior?

Easier to follow the documentation

## Environment

<pre><code>
Libs:
- react version: 18.2.0
- reaviz version: 13.1.13

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.16.0  
- Platform:  Windows 

Others:

</code></pre>

**Comment by amcdnl** [comment]
There is no `getXScale` in the code. Where did you find this?
